require('dotenv').config()
const express = require('express')
const server = express()
server.use(express.json())
const routes = require('./src/routes')
server.use(routes)
server.listen(process.env.PORT, () => console.log(`Server listening on port:::${process.env.PORT}`))